/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Juego;
import javax.swing.ImageIcon;

/**
 *
 * @author Edison
 */
public class Ahorcado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    Juego[] p;
    Juego palabra1;
    Juego palabra2, palabra3, palabra4, palabra5, palabra6, palabra7, palabra8, palabra9, palabra10;
    Juego pr;
    char[] letra;
    int c, cn, cl;
    ImageIcon i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11;

    public Ahorcado() {
        initComponents();
        cn = 0;
        i1 = new ImageIcon("1.png");
        i2 = new ImageIcon("2.png");
        i3 = new ImageIcon("3.png");
        i4 = new ImageIcon("4.png");
        i5 = new ImageIcon("5.png");
        i6 = new ImageIcon("6.png");
        i7 = new ImageIcon("7.png");
        i8 = new ImageIcon("8.png");
        i9 = new ImageIcon("9.png");
        i10 = new ImageIcon("10.png");
        i11 = new ImageIcon("11.png");;
        c = 0;
        p = new Juego[10];
        palabra1 = new Juego();
        palabra2 = new Juego();
        palabra3 = new Juego();
        palabra4 = new Juego();
        palabra5 = new Juego();
        palabra6 = new Juego();
        palabra7 = new Juego();
        palabra8 = new Juego();
        palabra9 = new Juego();
        palabra10 = new Juego();
        pr = new Juego();
        palabra1.setPalabra("monitor");
        palabra1.setPista("PARTE DE COMPUTADORA");
        p[0] = palabra1;
        palabra2.setPalabra("tela");
        palabra2.setPista("SASTRE");
        p[1] = palabra2;
        palabra3.setPalabra("raton");
        palabra3.setPista("ALCANTARIILADO");
        p[2] = palabra3;
        palabra4.setPalabra("internet");
        palabra4.setPista("MEDIO DE COMUNICACION");
        p[3] = palabra4;
        palabra5.setPalabra("choclo");
        palabra5.setPista("PRDOCUTO DE SIEMBRAS");
        p[4] = palabra5;
        palabra6.setPalabra("zhumir");
        palabra6.setPista("ALCOHOL");
        p[5] = palabra6;
        palabra7.setPalabra("ateo");
        palabra7.setPista("RELIGION");
        p[6] = palabra7;
        palabra8.setPalabra("cuenca");
        palabra8.setPista("EQUIPO DEPORTIVO");
        p[7] = palabra8;
        palabra9.setPalabra("estomago");
        palabra9.setPista("PARTE DEL CUERPO");
        p[8] = palabra9;
        palabra10.setPalabra("zapato");
        palabra10.setPista("VESTUARIO");
        p[9] = palabra10;
        generarPalabra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        l1 = new javax.swing.JTextField();
        l2 = new javax.swing.JTextField();
        l3 = new javax.swing.JTextField();
        l4 = new javax.swing.JTextField();
        l5 = new javax.swing.JTextField();
        l6 = new javax.swing.JTextField();
        l7 = new javax.swing.JTextField();
        l8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlPista = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        otrap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/1.png"))); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 590));

        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 25, 25));

        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 25, 25));

        l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3ActionPerformed(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 25, 25));

        l4.setToolTipText("");
        l4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4ActionPerformed(evt);
            }
        });
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 25, 25));

        l5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l5ActionPerformed(evt);
            }
        });
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 25, 25));

        l6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l6ActionPerformed(evt);
            }
        });
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 25, 25));

        l7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l7ActionPerformed(evt);
            }
        });
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 25, 25));

        l8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l8ActionPerformed(evt);
            }
        });
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 25, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pista:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 70, 40));

        jlPista.setBackground(new java.awt.Color(102, 255, 204));
        jlPista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlPista.setForeground(new java.awt.Color(204, 204, 0));
        jlPista.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jlPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 260, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 130, 40));

        resultado.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 310, 48));

        otrap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otrap.setText("Otra Palabra");
        otrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otrapActionPerformed(evt);
            }
        });
        getContentPane().add(otrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        if (l1.getText().equals(String.valueOf(letra[0]))) {
            l1.setEditable(false);
            cn++;
            comprovarVictoria();
        } else {
            error();
        }
    }//GEN-LAST:event_l1ActionPerformed

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        if (l2.getText().equals(String.valueOf(letra[1]))) {
            l2.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_l2ActionPerformed

    private void l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ActionPerformed
        if (l3.getText().equals(String.valueOf(letra[2]))) {
            l3.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_l3ActionPerformed

    private void l4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4ActionPerformed
        if (l4.getText().equals(String.valueOf(letra[3]))) {
            l4.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_l4ActionPerformed

    private void l5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l5ActionPerformed
        if (l5.getText().equals(String.valueOf(letra[4]))) {
            l5.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_l5ActionPerformed

    private void l6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l6ActionPerformed
        if (l6.getText().equals(String.valueOf(letra[5]))) {
            l6.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_l6ActionPerformed

    private void l7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l7ActionPerformed
        if (l7.getText().equals(String.valueOf(letra[6]))) {
            l7.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_l7ActionPerformed

    private void l8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l8ActionPerformed
        if (l8.getText().equals(String.valueOf(letra[7]))) {
            l8.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_l8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void otrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otrapActionPerformed
        // TODO add your handling code here:
        dispose();
        Ahorcado.main (null);
        
    }//GEN-LAST:event_otrapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlPista;
    private javax.swing.JTextField l1;
    private javax.swing.JTextField l2;
    private javax.swing.JTextField l3;
    private javax.swing.JTextField l4;
    private javax.swing.JTextField l5;
    private javax.swing.JTextField l6;
    private javax.swing.JTextField l7;
    private javax.swing.JTextField l8;
    private javax.swing.JButton otrap;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables

    private void generarPalabra() {
        int n = (int) (Math.random() * 10);
        pr = p[n];
        jlPista.setText(pr.getPista());
        if (pr.getPalabra().length() == 4) {
            l8.setVisible(false);
            l7.setVisible(false);
            l6.setVisible(false);
            l5.setVisible(false);
        } else if (pr.getPalabra().length() == 5) {
            l8.setVisible(false);
            l7.setVisible(false);
            l6.setVisible(false);
        } else if (pr.getPalabra().length() == 6) {
            l8.setVisible(false);
            l7.setVisible(false);
        } else if (pr.getPalabra().length() == 7) {
            l8.setVisible(false);
        }
        n = (int) (Math.random() * pr.getPalabra().length());
        letra = pr.getPalabra().toCharArray();
        char l = letra[n];
        if (l == letra[0]) {
            l1.setText(String.valueOf(l));
            l1.setEditable(false);
            cn++;
        }
        if (l == letra[1]) {
            l2.setText(String.valueOf(l));
            l2.setEditable(false);
            cn++;
        }
        if (l == letra[2]) {
            l3.setText(String.valueOf(l));
            l3.setEditable(false);
            cn++;
        }
        if (l == letra[3]) {
            l4.setText(String.valueOf(l));
            l4.setEditable(false);
            cn++;
        }
        if (letra.length > 4) {
            if (l == letra[4]) {
                l5.setText(String.valueOf(l));
                l5.setEditable(false);
                cn++;
            }
            if (letra.length > 5) {
                if (l == letra[5]) {
                    l6.setText(String.valueOf(l));
                    l6.setEditable(false);
                    cn++;
                }
                if (letra.length > 6) {
                    if (l == letra[6]) {
                        l7.setText(String.valueOf(l));
                        l7.setEditable(false);
                        cn++;
                    }
                    if (letra.length > 7) {
                        if (l == letra[7]) {
                            l8.setText(String.valueOf(l));
                            l8.setEditable(false);
                            cn++;
                        }
                    }
                }

            }

        }

    }

    private void error() {
        c++;
        if (c == 1) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/2.png")));
        } else if (c == 2) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/3.png")));
        } else if (c == 3) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/4.png")));
        } else if (c == 4) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/5.png")));
        } else if (c == 5) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/6.png")));
        } else if (c == 6) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/7.png")));
        } else if (c == 7) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/8.png")));
        } else if (c == 8) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/9.png")));
        } else if (c == 9) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/10.png")));
        } else if (c == 10) {
            imagen.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/11.png")));
            l1.setEditable(false);
            l2.setEditable(false);
            l3.setEditable(false);
            l4.setEditable(false);
            l5.setEditable(false);
            l6.setEditable(false);
            l7.setEditable(false);
            l8.setEditable(false);
            resultado.setText("Perdiste");
        }

    }

    private void comprovarVictoria() {
        if(cn == pr.getPalabra().length()){
            resultado.setText("Ganaste");
        }
    }
}
